version: "3"
services:
  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      ports:
        - "80:80"
      depends_on:
        - client
  client:
      container_name: client
      restart: always
      build: 
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      links:
        - app
      depends_on:
        - app
      env_file:
        - ./server/.env
      volumes: 
        - ./client:/client
  app:
    container_name: api
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    volumes: 
      - .server:/elec-meter
  postgres:
    container_name: postgres
    build: 
      context: ./server
      dockerfile: pg.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./server/postgresdata:/var/lib/postgresql/rca_auth
      - ./server/src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ntwaricliberi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ntwari@C232_2
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin:Z
    depends_on:
      - postgres
volumes:
  db-data:
  pgadmin-data:
  elec-meter:
  client: